@startuml expense-tracker-design

title Expense tracker - Diagrama de clases

!include controllers.puml
!include services.puml
!include repositories.puml
!include data.puml
!include domain.puml
!include dtos.puml
!include exception.puml
!include utils.puml
!include validators.puml

UserService *-- IValidation
ExpenseService *-- IValidation
IncomeService *-- IValidation
BudgetService *-- IValidation
GoalService *-- IValidation
AuthService *-- IValidation
AuthService *-- PasswordHasher
AuthService *-- JwtTokenGenerator

UserRepository *-- DbConnection
ExpenseRepository *-- DbConnection
IncomeRepository *-- DbConnection
BudgetRepository *-- DbConnection
GoalRepository *-- DbConnection

UserService *-- IUserRepository
ExpenseService *-- IExpenseRepository
IncomeService *-- IIncomeRepository
BudgetService *-- IBudgetRepository
GoalService *-- IGoalRepository

UserController *-- IUserService
ExpenseController *-- IExpenseService
IncomeController *-- IIncomeService
BudgetController *-- IBudgetService
GoalController *-- IGoalService
AuthController *-- IAuthService

@enduml